name: CI/CD Backend Ventas

on:
  push:
    branches:
      - deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Login a Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build y Push imagen Docker
        uses: docker/build-push-action@v5
        with:
          context: ./Springboot-API-REST
          push: true
          tags: alkbil/backend-ventas-innovatech:latest

      - name: Desplegar en EC2-Backend vía bastión
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_BACKEND_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          proxy_host: ${{ secrets.EC2_FRONTEND_HOST }}
          proxy_username: ec2-user
          proxy_key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull alkbil/backend-ventas-innovatech:latest
            docker stop backend-ventas || true
            docker rm backend-ventas || true
            docker run -d \
              --name backend-ventas \
              --restart always \
              -p 8080:8080 \
              -e SPRING_DATASOURCE_URL=${{ secrets.DB_URL }} \
              -e DB_USERNAME=${{ secrets.DB_USERNAME }} \
              -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
              alkbil/backend-ventas-innovatech:latest
